/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface ExampleCounter {
        /**
          * Name to display
         */
        "name": string;
    }
    interface ExampleFetch {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLExampleCounterElement extends Components.ExampleCounter, HTMLStencilElement {
    }
    var HTMLExampleCounterElement: {
        prototype: HTMLExampleCounterElement;
        new (): HTMLExampleCounterElement;
    };
    interface HTMLExampleFetchElement extends Components.ExampleFetch, HTMLStencilElement {
    }
    var HTMLExampleFetchElement: {
        prototype: HTMLExampleFetchElement;
        new (): HTMLExampleFetchElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "example-counter": HTMLExampleCounterElement;
        "example-fetch": HTMLExampleFetchElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface ExampleCounter {
        /**
          * Name to display
         */
        "name"?: string;
    }
    interface ExampleFetch {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "example-counter": ExampleCounter;
        "example-fetch": ExampleFetch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "example-counter": LocalJSX.ExampleCounter & JSXBase.HTMLAttributes<HTMLExampleCounterElement>;
            "example-fetch": LocalJSX.ExampleFetch & JSXBase.HTMLAttributes<HTMLExampleFetchElement>;
        }
    }
}
